name: website-screenshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://raidionics.github.io/
        destination: screenshot.png

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      continue-on-error: false
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: website-screenshot.yml
        workflow_conclusion: success
        branch: master
        event: push
        name: screenshot
        repo: raidionics/raidionics.github.io

    - name: Commit files
      run: |
        git add screenshot.png
        git commit -m "Update snapshot of website [skip ci]" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.master }}

    - name: Update screenshot in release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: raidionics/raidionics.github.io
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/screenshot.png
        asset_name: screenshot.png
        file_glob: true
        tag: screenshot-website
        overwrite: true
